name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: url_shortener_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d url_shortener_test"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    env:
      REDIS_URL: redis://localhost:6379
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/url_shortener_test
      BETTER_AUTH_SECRET: test-secret-for-ci-only
      BETTER_AUTH_URL: http://localhost:5000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.18.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm --filter @repo/database generate

      - name: Build database
        run: pnpm --filter @repo/database build

      - name: Build Redis package
        run: pnpm --filter @repo/redis build

      - name: Build backend
        run: pnpm --filter @repo/backend build

      - name: Run database migrations
        run: pnpm --filter @repo/database migrate:deploy

      - name: Run tests
        run: pnpm --filter @repo/backend test